id: P5BB5C91C
initial_creation_type: input
source_metadata:
  title: Dudjom Rinpoche Series
  language: bo
  description: 'We present the following texts by Kyabje Dudjom Rinpoche Jikdral Yeshe
    Dorje (bdud ''joms ''jigs bral ye shes rdo rje, 1904–1987), the renowned yogi
    and scholar and first appointed head of the Nyingma school in exile:'
  volume:
    7a483596a063480683961ea41d9f9768:
      title: The Mirror Clearly Showing What to Adopt and Abandon
      parent: Advice
    0036472ea31645a9b57cb822883affd4:
      title: The Concise Benefits of the Festival of the Tenth Day
      parent: Benefits
    0a159924ccb14164bc42749960c77373:
      title: 'The Light of Primordial Wisdom: An Instruction Manual for the Primordially
        Pure Perfection Stage of the Powerful & Wrathful Dorje Drolö, Conqueror of
        Demons'
      parent: Commentaries
    c0589639bd8c49a9ac68d62957ea2832:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Commentaries
    794787357acc4f8982d2623e31f42ed4:
      title: Concise Consecration
      parent: Consecration
    c5ee1ca2fa4242dbae15d6298535cdec:
      title: A Brief Petitionary Offering to the Mātṛkā Pukkasī, Local Protectress
        of the Jarung Kashor Stūpa
      parent: Dharma Protectors
    cb021f22a6584f77902ea28f98c253fa:
      title: Dzogchen Aspiration Prayer
      parent: Dzogchen
    ea3a584902264c939c8857745a1ea762:
      title: 'Spontaneous Song of the Genuine Nature: A Prayer of Calling the Guru
        from Afar'
      parent: Dzogchen
    97777965f1944a00bb1e3a010148f352:
      title: Summary of Striking the Vital Point in Three Statements
      parent: Dzogchen
    38df998118464f20ad301fd2b05e89e2:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Guru Rinpoche Prayers
    6e9a6b17b8924b95819a7eaa61c9dde0:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Guru Rinpoche Prayers
    0f5907b717f3428eb7900a478729e772:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Guru Rinpoche Prayers
    f878bdfb07d04801bd61a4a663734e1c:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Guru Rinpoche Prayers
    6d3751c4927743db8553caaed18a2514:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Guru Rinpoche Prayers
    b7f19fbf02324517b15ee15b1f47917f:
      title: A Concise Lineage Prayer
      parent: Lineage Prayers
    59a7b40cdab54c18bfb21f70c065ed8f:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    a3428a8be9ab45a2ba792815e4b72142:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    d9fc4278f4244efca20d3eaafc87c443:
      title: Prayer for the Long Life of Dzogchen Rinpoche
      parent: Long Life Prayers
    506e9bb2287545989677f9c6cd57b8cf:
      title: Prayer for the Long Life of His Holiness the Dalai Lama
      parent: Long Life Prayers
    66ad34ffcbbb460d8f27170f76e0bef5:
      title: 'The Drumbeat of Immortality: A Prayer for the Long Life of the Great
        Tertön Dudjom Jigdral Yeshe Dorje'
      parent: Long Life Prayers
    73401cf1a8744d76a24c84987925eafc:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Ngöndro
    af78a855bf41414b9b43982e07cad1fb:
      title: Brief Notes on the Visualization for the Concise Recitation of the Pure
        Vision Preliminary Practice
      parent: Ngöndro
    be03acc1f2434f2d8f1178074f64bbf0:
      title: Brief Red Sur Offering
      parent: Offering
    283b0804089e4e0a850f53a4447e26e6:
      title: Brief Sur Offering
      parent: Offering
    7c9a7337d51947c4b2acffa97d961e2b:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayers
    01ff70a3a2864092b8a2e514c04d79c2:
      title: Essence and Embodiment of All the Buddhas
      parent: Prayers
    c0965f887eb04bcc8f8f2cb7163b13bb:
      title: Prayer to the Three Great Stūpas of Kathmandu
      parent: Prayers
    1d3ea0329b6a4245b1c0a8f224583a46:
      title: A Daily 'Hand-Clapping' Practice of Siṃhamukhā
      parent: Sādhanas
    ca48a7aa981c4e8cb2f03d5c067356a5:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    2209ad3640034ac795cb986e8f7c1493:
      title: A Daily Practice of Lama Sangdü
      parent: Sādhanas
    8ef5bfddd6674f2c9a7eb3472bc6120d:
      title: A Daily Practice of Ucchuṣma
      parent: Sādhanas
    b31c47ef04c440bb9fe608377f24cee6:
      title: Condensed Daily Practice of The Heart Essence of the Sublime Lady of
        Immortality
      parent: Sādhanas
    b3a28d415ae34acd97df36c21837ab8d:
      title: Daily Practice of Dorje Gotrab
      parent: Sādhanas
    fc713ded64a74e29b8cf536a2c7013e8:
      title: 'The Blazing Tower: A Daily Practice of Uṣṇīṣa-Sitātapatrā'
      parent: Sādhanas
    da94970da78e4cdd8f9e81d09e798a29:
      title: 'The Concentrated Essence: A Sādhana of Yeshe Tsogyal'
      parent: Sādhanas
    7800caf5fc8948cbb855780c67b325d7:
      title: The Daily Practice of the Secret Sādhana of Dorje Drolö
      parent: Sādhanas
    ab0b16eb6f3941f889ec9e9c29f7b588:
      title: The Essential Daily Practice of Vajrakīla
      parent: Sādhanas
    642853209ddc46dba40cfdb7bee50a05:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    51968331a77042279c4c2e2379ab8119:
      title: 'Divine Blue Water: A Contamination Purifying Smoke Offering by the Great
        Master Padmasambhava'
      parent: Sang Offering
    252fdabbb00742a5aeddb91506065d57:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
    9925361f6bed41ecb5a5e61d23b6a5a3:
      title: 'The Concentrated Essence: A Concise Practice of Healing and Purifying
        (Sojong) the Three Sets of Vows'
      parent: Sojong
    3642d23f546d4ab99ce92316f34e6f87:
      title: Remainder Torma Offering for Seven-Line Prayer Guru Yoga
      parent: Tsok
    0ac8d588d39e461f8842d52920e85e74:
      title: The Brief Tsok Feast Offering Prayer from 'The Profound Path of the Ḍākinīs'
        Heart Drop'
      parent: Tsok
    c19da31ae1ef447cb501e8a37b72fedf:
      title: A Daily Practice of Vajraṇakhī
      parent: Vajraṇakhī
created_at: '2022-02-28T23:10:30.058510'
last_modified_at: '2022-02-28T23:10:30.058513'
statistics:
  total_words: 30366
  total_non_words: 3770
quality:
  non_words_ratio: 0.12
